name: Build and push Docker image
on:
  push:
    branches:
    - main
jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PAT }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M%S')"  
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: >
          ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:${{ steps.date.outputs.date }}, 
          ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest
          