apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: secondapp
  template:
    metadata:
      labels:
        app: secondapp
        training: gitops-basic
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/nginx/html
      volumes:
        - name: config-volume
          configMap:
            name: secondapp-config